name: add tag to repo
on:
  pull_request:

# this permission is required
# see: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions:
  contents: write

jobs:
  create-tag-and-push:
    runs-on: ubuntu-latest
    needs: check-version-change
    if: ${{needs.prev.outputs.version}}
    steps:
      - uses: actions/checkout@v3
      - name: create tag and push
        run: |
          git tag v${{needs.prev.outputs.version}}
          git push origin v${{needs.prev.outputs.version}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
